task:
  name: MacOS
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  test_script:
    - echo|cpan App::cpanminus
    - /Users/admin/perl5/bin/cpanm -v --installdeps .
    - export PERL5LIB=/Users/admin/perl5/lib/perl5
    - perl Makefile.PL verbose
    - make test
