on: [push, pull_request]
name: Linux install

jobs:
  build:
    runs-on: 'macos-15'
    steps:
      - uses: actions/checkout@v4
      - name: Setup Perl environment
        uses: shogo82148/actions-setup-perl@v1
      - name: Test and build
        run: |
          cpanm --installdeps .
          perl Makefile.PL
          make test
          make dist
      - uses: actions/upload-artifact@v4
        with:
          name: dist-for-installation-test
          path: '*.tar.gz'
          retention-days: 1
  install-linux:
    runs-on: 'ubuntu-latest'
    needs: build
    container:
      image: perl:5.34
    steps:
      - uses: actions/download-artifact@v4.2.1
        with:
          name: dist-for-installation-test
      - name: Install on Linux
        run: |
          # cpanm ExtUtils::MakeMaker Test::Pod Test::Pod::Coverage || cat /home/runner/.cpanm/work/*/build.log
          # perl -Mparent -e0 || cpanm parent
          apt update && apt install sudo # this shouldn't be necessary!
          sudo true
          cpanm *.tar.gz || cat /github/home/.cpanm/work/*/build.log
